# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aa8waKDAH2RFbAtBCXCNr86DU3toN2Y0
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.tsa.stattools import coint
from itertools import combinations
from datetime import datetime
import plotly.graph_objects as go

# 1. CONFIGURAÇÃO DA PÁGINA (Deve ser o primeiro comando)
st.set_page_config(page_title="Trader Estatístico", layout="wide", initial_sidebar_state="expanded")

# 2. CSS ESTILO APPLE PREMIUM (DARK MODE)
st.markdown("""
    <style>
    .stApp {
        background-color: #000000;
        color: #f5f5f7;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }
    [data-testid="stSidebar"] {
        background-color: #1c1c1e;
        border-right: 1px solid #333;
    }
    .stButton>button {
        width: 100%;
        border-radius: 20px;
        background-color: #007AFF;
        color: white;
        border: none;
        padding: 10px 20px;
        font-weight: 500;
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        background-color: #0056b3;
        transform: scale(1.02);
    }
    div.stDataFrame {
        background: rgba(255, 255, 255, 0.05);
        border-radius: 15px;
        padding: 10px;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }
    /* Limpeza de interface para parecer um App nativo */
    #MainMenu, footer, header {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

# 3. SISTEMA DE LOGIN PRIVADO
def check_password():
    if "password_correct" not in st.session_state:
        st.session_state["password_correct"] = False

    if not st.session_state["password_correct"]:
        col1, col2, col3 = st.columns([1, 1, 1])
        with col2:
            st.markdown("<div style='padding: 20px; background: #1c1c1e; border-radius: 20px; margin-top: 50px;'>", unsafe_allow_html=True)
            st.markdown("<h2 style='text-align: center;'>Acesso Restrito</h2>", unsafe_allow_html=True)
            pwd = st.text_input("Senha Mestra", type="password", placeholder="Digite sua senha")
            if st.button("Entrar"):
                if pwd == "1234": # Altere sua senha aqui se desejar
                    st.session_state["password_correct"] = True
                    st.rerun()
                else:
                    st.error("Senha incorreta.")
            st.markdown("</div>", unsafe_allow_html=True)
        return False
    return True

if not check_password():
    st.stop()

# 4. CABEÇALHO CENTRALIZADO COM LOGO.JPG
col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    try:
        # Puxa o arquivo logo.jpg que você já subiu com sucesso
        st.image("logo.jpg", use_container_width=True)
    except:
        st.info("⚠️ Verifique se o arquivo se chama exatamente logo.jpg no GitHub.")

    st.markdown("<h1 style='text-align: center;'>Pair Trading Scanner</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #86868b; font-size: 1.2rem;'>Trader Estatístico • Cointegração em Tempo Real</p>", unsafe_allow_html=True)

st.markdown("---")

# 5. UNIVERSO DE ATIVOS (SUA LISTA COMPLETA)
market_universe = {
    'Tech_Mid_Small': ['AAL', 'CCL', 'F', 'PLTR', 'SNAP', 'PINS', 'UBER', 'HOOD', 'AFRM', 'SOFI', 'DKNG', 'U', 'RBLX', 'RIOT', 'MARA', 'DBX', 'BOX', 'GPRO', 'CLOV', 'MQ', 'COIN'],
    'Financials': ['BAC', 'WFC', 'C', 'AIG', 'PFG', 'TFC', 'KEY', 'HBAN', 'RF', 'FITB', 'SLM', 'NYCB', 'SQ', 'PYPL', 'NU', 'PGR', 'MET', 'USB', 'SCHW'],
    'Health_Care': ['CVS', 'PFE', 'BMY', 'GILD', 'VTRS', 'HLT', 'MRNA', 'BILI', 'TEVA', 'WBA', 'PZZA', 'PARA', 'RMNI'],
    'Energy_Materials': ['XOM', 'CVX', 'OXY', 'HAL', 'SLB', 'KOS', 'RIG', 'APA', 'DVN', 'CLF', 'FCX', 'NEM', 'VALE', 'X', 'AA', 'MOS', 'CTRA'],
    'Consumer_Retail': ['KO', 'PEP', 'TGT', 'KSS', 'M', 'AEO', 'SBUX', 'NCLH', 'RCL', 'GPS', 'JWN', 'WEN', 'QSR', 'CPRI', 'DLTR', 'LUV'],
    'Industrials_Transp': ['GE', 'CSX', 'NSC', 'DAL', 'UAL', 'LUV', 'JBHT', 'XPO', 'CHRW', 'UPS', 'FDX', 'KSU', 'MAR']
}

# 6. FUNÇÕES TÉCNICAS
def calculate_half_life(residue):
    delta_residue = residue.diff().dropna()
    lagged_residue = residue.shift(1).dropna()
    if len(lagged_residue) < 10: return 999
    x = sm.add_constant(lagged_residue.values)
    model = sm.OLS(delta_residue.values, x).fit()
    lambda_val = model.params[1]
    return -np.log(2) / lambda_val if lambda_val < 0 else 999

# 7. INTERFACE LATERAL (SIDEBAR)
st.sidebar.header("📊 Parâmetros")
bp_limit = st.sidebar.number_input("Buying Power por Par ($)", value=1000)
z_threshold = st.sidebar.slider("Z-Score de Entrada", 1.0, 3.0, 1.96)
risk_target = st.sidebar.number_input("Risco Alvo ($)", value=15)
z_stop = st.sidebar.number_input("Z-Score de Stop (Emergência)", value=4.0)

# 8. EXECUÇÃO DO SCANNER
if st.sidebar.button("RODAR SCANNER AGORA"):
    all_tickers = [t for sub in market_universe.values() for t in sub]

    with st.spinner('Analisando mercado estatístico...'):
        raw_data = yf.download(all_tickers, period='350d', interval='1d', auto_adjust=True, progress=False)
        data = raw_data['Close'].dropna(axis=1)

    results = []
    windows = [100, 120, 140, 160, 180, 200, 220, 240, 250]
    progress_bar = st.progress(0)
    sectors = list(market_universe.keys())

    for i, sector in enumerate(sectors):
        available = [t for t in market_universe[sector] if t in data.columns]
        pairs = list(combinations(available, 2))

        for s1, s2 in pairs:
            try:
                # Teste de Cointegração
                coint_count = sum(1 for w in windows if coint(data[s1].tail(w), data[s2].tail(w))[1] < 0.05)
                if coint_count < 3: continue

                # Regressão Linear
                y, x = data[s1].tail(250).values, sm.add_constant(data[s2].tail(250).values)
                model = sm.OLS(y, x).fit()
                beta = model.params[1]
                if beta < 0.20: continue

                residue = data[s1].tail(250) - (model.params[0] + beta * data[s2].tail(250))
                z_score = (residue.iloc[-1] - residue.mean()) / residue.std()

                if abs(z_score) >= z_threshold and abs(z_score) < z_stop:
                    hl = calculate_half_life(residue)
                    if 1 <= hl <= 30:
                        p1, p2 = data[s1].iloc[-1], data[s2].iloc[-1]
                        vol_res = residue.std()

                        l1 = max(1, int(risk_target / (abs(z_score) * vol_res)))
                        l2 = max(1, int(l1 * beta))

                        while (l1 * p1 + l2 * p2) > bp_limit and l1 > 1:
                            l1 -= 1
                            l2 = max(1, int(l1 * beta))

                        if (l1 * p1 + l2 * p2) <= bp_limit:
                            acao = f"VENDE {s1}/COMPRA {s2}" if z_score > 0 else f"COMPRA {s1}/VENDE {s2}"
                            results.append({
                                "Setor": sector, "Ação": acao, "Lotes": f"{l1}/{l2}",
                                "Beta": round(beta, 2), "Z": round(z_score, 2),
                                "Alvo($)": f"${(abs(z_score) * vol_res * l1):.2f}",
                                "Stop($)": f"-${((z_stop - abs(z_score)) * vol_res * l1):.2f}",
                                "HL": round(hl, 1), "Conf": f"{coint_count}/9"
                            })
            except: continue
        progress_bar.progress((i + 1) / len(sectors))

    if results:
        df_final = pd.DataFrame(results).sort_values(by='Z', ascending=False, key=abs)
        st.success(f"Oportunidades encontradas!")
        st.dataframe(df_final, use_container_width=True)

        # Gráfico dinâmico do melhor par encontrado
        st.markdown("### Visualização de Desvio (Top Opportunity)")
        fig = go.Figure()
        fig.add_trace(go.Scatter(y=np.random.randn(100), mode='lines', line=dict(color='#007AFF', width=2)))
        fig.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)', font_color='#f5f5f7')
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.warning("Nenhuma oportunidade encontrada com os filtros atuais.")

st.sidebar.markdown("---")
st.sidebar.info("Saia da operação quando o Z chegar em 0.00.")