# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTCz4Sa020NifMvng78FfRdiMu7niuuR
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.tsa.stattools import coint
from itertools import combinations
from datetime import datetime
import plotly.graph_objects as go

# 1. CONFIGURAÇÃO ÚNICA DA PÁGINA (Deve ser o primeiro comando Streamlit)
st.set_page_config(page_title="Trader Estatístico", layout="wide", initial_sidebar_state="expanded")

# 2. CSS CUSTOMIZADO (ESTILO APPLE PREMIUM)
st.markdown("""
    <style>
    .stApp {
        background-color: #000000;
        color: #f5f5f7;
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    }
    [data-testid="stSidebar"] {
        background-color: #1c1c1e;
        border-right: 1px solid #333;
    }
    .stButton>button {
        width: 100%;
        border-radius: 20px;
        background-color: #007AFF;
        color: white;
        border: none;
        padding: 10px 20px;
        transition: all 0.3s ease;
    }
    div.stDataFrame {
        background: rgba(255, 255, 255, 0.05);
        border-radius: 15px;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }
    #MainMenu, footer, header {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

# 3. CABEÇALHO CENTRALIZADO COM LOGO.JPG
col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    try:
        # Puxa o arquivo logo.jpg que você já subiu com sucesso
        st.image("logo.jpg", use_container_width=True)
    except:
        st.info("⚠️ Verifique se o arquivo se chama exatamente logo.jpg no GitHub.")

    st.markdown("<h1 style='text-align: center;'>Pair Trading Scanner</h1>", unsafe_allow_html=True)
    st.markdown("<h3 style='text-align: center; color: #86868b;'>Trader Estatístico</h3>", unsafe_allow_html=True)

st.markdown("---")

# 4. UNIVERSO DE ATIVOS
market_universe = {
    'Tech_Mid_Small': ['AAL', 'CCL', 'F', 'PLTR', 'SNAP', 'PINS', 'UBER', 'HOOD', 'AFRM', 'SOFI', 'DKNG', 'U', 'RBLX', 'RIOT', 'MARA', 'DBX', 'BOX', 'GPRO', 'CLOV', 'MQ', 'COIN'],
    'Financials': ['BAC', 'WFC', 'C', 'AIG', 'PFG', 'TFC', 'KEY', 'HBAN', 'RF', 'FITB', 'SLM', 'NYCB', 'SQ', 'PYPL', 'NU', 'PGR', 'MET', 'USB', 'SCHW'],
    'Consumer_Retail': ['KO', 'PEP', 'TGT', 'KSS', 'M', 'AEO', 'SBUX', 'NCLH', 'RCL', 'GPS', 'JWN', 'WEN', 'QSR', 'CPRI', 'DLTR', 'LUV'],
    'Energy_Materials': ['XOM', 'CVX', 'OXY', 'HAL', 'SLB', 'KOS', 'RIG', 'APA', 'DVN', 'CLF', 'FCX', 'NEM', 'VALE', 'X', 'AA', 'MOS', 'CTRA']
}

# 5. FUNÇÕES TÉCNICAS
def calculate_half_life(residue):
    delta_residue = residue.diff().dropna()
    lagged_residue = residue.shift(1).dropna()
    if len(lagged_residue) < 10: return 999
    x = sm.add_constant(lagged_residue.values)
    model = sm.OLS(delta_residue.values, x).fit()
    lambda_val = model.params[1]
    return -np.log(2) / lambda_val if lambda_val < 0 else 999

# 6. INTERFACE LATERAL
st.sidebar.header("📊 Parâmetros")
bp_limit = st.sidebar.number_input("Buying Power por Par ($)", value=1000)
z_threshold = st.sidebar.slider("Z-Score de Entrada", 1.0, 3.0, 1.96)
risk_target = st.sidebar.number_input("Risco Alvo ($)", value=15)

# 7. EXECUÇÃO
if st.sidebar.button("RODAR SCANNER AGORA"):
    all_tickers = [t for sub in market_universe.values() for t in sub]
    with st.spinner('Analisando mercado estatístico...'):
        data = yf.download(all_tickers, period='350d', progress=False)['Close'].dropna(axis=1)

    results = []
    progress_bar = st.progress(0)
    sectors = list(market_universe.keys())

    for i, sector in enumerate(sectors):
        available = [t for t in market_universe[sector] if t in data.columns]
        for s1, s2 in combinations(available, 2):
            try:
                p_val = coint(data[s1].tail(250), data[s2].tail(250))[1]
                if p_val < 0.05:
                    y, x = data[s1].tail(250).values, sm.add_constant(data[s2].tail(250).values)
                    model = sm.OLS(y, x).fit()
                    beta = model.params[1]
                    residue = data[s1].tail(250) - (model.params[0] + beta * data[s2].tail(250))
                    z_score = (residue.iloc[-1] - residue.mean()) / residue.std()

                    if abs(z_score) >= z_threshold:
                        results.append({
                            "Setor": sector, "Ação": f"{s1}/{s2}",
                            "Beta": round(beta, 2), "Z": round(z_score, 2),
                            "Alvo($)": f"${(abs(z_score) * residue.std() * 1):.2f}"
                        })
            except: continue
        progress_bar.progress((i + 1) / len(sectors))

    if results:
        st.dataframe(pd.DataFrame(results), use_container_width=True)
    else:
        st.warning("Nenhuma oportunidade encontrada.")       
